-- ==========================================
-- SCHEMA RECONSTRUCTION FOR LUZ DO CAMINHO
-- ==========================================
-- This script contains all the table definitions, unique constraints, 
-- indexes, Row-Level Security (RLS) policies, and seed data 
-- required to reconstruct the Supabase database.
--
-- Copy and paste this entire script into your Supabase SQL Editor 
-- (https://supabase.com/dashboard/project/_/sql) and run it.

-- --------------------------------------------------
-- 1. FAVORITES TABLE (For favoriting verses)
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS public.favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    verse_ref TEXT NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT unique_user_verse_ref UNIQUE (user_id, verse_ref)
);

-- --------------------------------------------------
-- 2. NOTES TABLE (For chapter annotations)
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS public.notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    book_abbrev TEXT NOT NULL,
    chapter_index INTEGER NOT NULL,
    text TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT unique_user_book_chapter UNIQUE (user_id, book_abbrev, chapter_index)
);

-- --------------------------------------------------
-- 3. CHAT MESSAGES TABLE (For assistant history)
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'model')),
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- --------------------------------------------------
-- 4. READING LOGS TABLE (For user reading streaks)
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS public.reading_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    read_date DATE DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT unique_user_read_date UNIQUE (user_id, read_date)
);

-- --------------------------------------------------
-- 5. PERFORMANCE INDEXES
-- --------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_favorites_user_id ON public.favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_notes_user_id ON public.notes(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_user_id ON public.chat_messages(user_id);
CREATE INDEX IF NOT EXISTS idx_reading_logs_user_id ON public.reading_logs(user_id);

-- --------------------------------------------------
-- 6. ROW LEVEL SECURITY (RLS) POLICIES
-- --------------------------------------------------

-- Enable RLS on all tables
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reading_logs ENABLE ROW LEVEL SECURITY;

-- Favorites Policies (User specific)
CREATE POLICY "Users can manage their own favorites" 
ON public.favorites FOR ALL 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Notes Policies (User specific)
CREATE POLICY "Users can manage their own notes" 
ON public.notes FOR ALL 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Chat Messages Policies (User specific)
CREATE POLICY "Users can manage their own chat messages" 
ON public.chat_messages FOR ALL 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Reading Logs Policies (User specific)
CREATE POLICY "Users can manage their own reading logs" 
ON public.reading_logs FOR ALL 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);
